### PR TITLE
done

### PR DESCRIPTION
**Pull request by creyo**

### CODE REVIEW

**Comment by creyo** [comment]
update

**Review by alirazaqureshi43 — APPROVED** [review]

**Review by alirazaqureshi43 — APPROVED** [review]

**Review by alirazaqureshi43 — APPROVED** [review]
approved-changes

**Review by alirazaqureshi43 — APPROVED** [review]
https://answers.netlify.com/t/delete-default-subdomain/14573

**Comment by alirazaqureshi43** [comment]
approved

**Comment by creyo** [comment]
ok

**Pull request closed without merging**
